# Generated by Django 5.2.8 on 2025-11-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('parque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.parque')),
            ],
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('extensao_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dificuldade', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ABERTA', 'ABERTA'), ('FECHADA', 'Fechada'), ('EM_MANUTENCAO', 'Em Manutenção')], default='ABERTA', max_length=15)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas', to='core.parque')),
            ],
        ),
    ]
