# Generated by Django 5.2.8 on 2025-11-09 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novidade',
            name='parque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novidades', to='core.parque'),
        ),
        migrations.AddField(
            model_name='novidade',
            name='trilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novidades', to='core.trilha'),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('EM_MANUTENCAO', 'Em Manutenção')], default='ABERTA', max_length=15),
        ),
    ]
