# Generated by Django 5.2.8 on 2025-11-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_novidade_parque_novidade_trilha_alter_trilha_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilha',
            name='dificuldade',
            field=models.IntegerField(choices=[(1, 'Fácil'), (2, 'Moderado'), (3, 'Difícil')], default=2, verbose_name='Dificuldade'),
        ),
    ]
