# Generated by Django 5.2.8 on 2025-11-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_trilha_dificuldade'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagem_url',
            field=models.URLField(blank=True, verbose_name='Imagem'),
        ),
    ]
