# Generated by Django 5.2.8 on 2025-11-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_horariofuncionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
